/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Store information. */
export interface StoreInfo {
  root: string
  collection: string
  count: number
}
/** Get the ZDS version. */
export declare function version(): string
/** Root information. */
export interface RootInfo {
  root: string
  batchSize: number
  mode: string
  isWritable: boolean
  collections: Array<string>
}
export type ZDSStore = ZdsStore
/** High-performance ZDS Store backed by Rust FastStore (JSONL-based). */
export declare class ZdsStore {
  /** Open a ZDS store. */
  static open(root: string, collection?: string | undefined | null, batchSize?: number | undefined | null): ZdsStore
  /** Get document by ID. */
  get(docId: string): any
  /** Put a document. */
  put(docId: string, doc: any): void
  /** Delete a document. */
  delete(docId: string): void
  /** Flush pending writes and refresh mmap. */
  flush(): void
  /** Close the store and flush pending writes. */
  close(): void
  /**
   * Write a complete JSONL blob (fastest bulk write path).
   * jsonl_data: Pre-serialized JSONL with one JSON object per line.
   * doc_ids: List of document IDs in order matching the lines.
   */
  writeJsonl(jsonlData: Buffer, docIds: Array<string>): number
  /** Scan and return raw JSON bytes (fastest read path). */
  scanRaw(): Array<Buffer>
  /**
   * Read entire JSONL file as a single buffer (fastest bulk read).
   * Returns the raw JSONL content - caller splits and parses.
   */
  readJsonlBlob(): Buffer
  /** Get document count. */
  get count(): number
  /** Check if document exists. */
  exists(docId: string): boolean
  /** Scan all documents. */
  scan(): Array<any>
  /** List all document IDs. */
  listDocIds(): Array<string>
  /** Get store info. */
  get info(): StoreInfo
}
/** Bulk write helper for high-throughput ingestion. */
export declare class BulkWriter {
  /** Create a new bulk writer. */
  static create(root: string, collection?: string | undefined | null, batchSize?: number | undefined | null): BulkWriter
  /** Put a document. */
  put(docId: string, doc: any): void
  /** Flush pending writes. */
  flush(): void
  /** Get current document count. */
  get count(): number
}
export type ZDSRoot = ZdsRoot
/**
 * Root handle for a ZDS store directory.
 *
 * This class represents a ZDS root directory without binding to a specific collection.
 * It allows opening multiple collections from the same root safely, avoiding corruption
 * when writing to multiple collections simultaneously.
 *
 * Example:
 *   const root = ZdsRoot.open('./data');
 *   const train = root.collection('train');
 *   const test = root.collection('test');
 *   train.put('doc1', { split: 'train' });
 *   test.put('doc1', { split: 'test' });
 */
export declare class ZdsRoot {
  /**
   * Open or create a ZDS root directory.
   *
   * @param root - Path to the ZDS root directory
   * @param batchSize - Default batch size for collections (default: 5000)
   * @param mode - Open mode: "r" for read-only, "rw" for read-write (default: "rw")
   */
  static open(root: string, batchSize?: number | undefined | null, mode?: string | undefined | null): ZdsRoot
  /** Get the root path. */
  get rootPath(): string
  /** Get the default batch size. */
  get batchSize(): number
  /** Get the open mode ("r" or "rw"). */
  get mode(): string
  /** Check if this root is writable. */
  get isWritable(): boolean
  /** Open a collection within this ZDS root. */
  collection(name: string, batchSize?: number | undefined | null): ZdsStore
  /** List all collections in this ZDS root. */
  listCollections(): Array<string>
  /** Check if a collection exists. */
  collectionExists(name: string): boolean
  /** Close the root and release any locks. */
  close(): void
  /** Get root info. */
  get info(): RootInfo
}
