/**
 * Type declarations for the native Rust bindings.
 * This file is auto-generated by napi-rs during build.
 */

export interface StoreInfo {
  root: string;
  collection: string;
  count: number;
}

export class ZDSStore {
  static open(root: string, collection?: string, batchSize?: number): ZDSStore;
  get(docId: string): unknown;
  put(docId: string, doc: unknown): void;
  delete(docId: string): void;
  exists(docId: string): boolean;
  flush(): void;
  close(): void;
  scan(): unknown[];
  listDocIds(): string[];
  getAt(index: number): unknown;
  get count(): number;
  get info(): StoreInfo;
}

export class BulkWriter {
  static create(root: string, collection?: string, batchSize?: number): BulkWriter;
  put(docId: string, doc: unknown): void;
  flush(): void;
  get count(): number;
}

export function version(): string;
